---
- hosts: all
  become: true

  roles:
    - roles/docker/install-docker

  tasks:
    - name: copy files
      copy:
        src: "{{item}}"
        dest: /home/rashid/demo
        owner: root
        group: root
        mode: 0777
      with_items:
        - index.html
        - docker-compose.yml

    - name: run docker-compose.yml
      docker_compose:
        project_src: /home/rashid/demo
