---
- hosts: all
  become: true

  roles:
    - {
        role: roles/docker/install-docker,
        when: setup_docker_ecosystem == 'true' or setup_docker_ecosystem == true,
      }

  tasks:
    - name: copy files
      copy:
        src: "{{item}}"
        dest: /home/rashid/demo
        owner: root
        group: root
        mode: 0777
      with_items:
        - index.html
        - docker-compose.yml

    - name: run docker-compose.yml
      docker_compose:
        project_src: /home/rashid/demo
