---
- hosts: all
  become: true

  tasks:
    - name: copy index file
      copy:
        src: index.html
        dest: /home/rashid/index.html
        owner: root
        group: root
        mode: 0777

    - name: Install docker.
      package:
        name: docker-ce
        state: present

    - name: Start docker service
      service:
        name: docker
        state: started
